spring:
  datasource:
    url: jdbc:h2:mem:objetivosDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console   # Console web do H2 disponível em http://localhost:8080/h2-console

  sql:
    init:
      mode: always        # Sempre rodar o schema.sql
      platform: h2

  jpa:
    hibernate:
      ddl-auto: none      # Não deixar o Hibernate sobrescrever o schema.sql
    show-sql: true        # Mostrar SQL no console
    properties:
      hibernate:
        format_sql: true
